#-----------------------------------------------
# config.system.yaml user setting
# 
# config.system.default.yamlの値をこのファイルで
# 上書きすることが出来ます。
#-----------------------------------------------

### 例 jQueryのバージョンを切り替える
# jquery_version : 1.11.1 # (2.1.1|2.0.3|1.11.1|1.10.1|1.9.1|1.8.3|1.7.2|1.6.4) 2.xはIE9〜